name: "LvMultiplesLanguages"
version: ${project.version}
main: codes.laivy.mlanguage.main.bukkit.LvMultiplesLanguagesBukkit
author: "ItsLaivy (DanielZinh#7616)"
api-version: 1.13

website: "https://laivy.codes/"

depend:
  - DataAPI-Java

commands:
  language:
    description: "The main language plugin"
    aliases: [lang]

libraries:
  - org.xerial:sqlite-jdbc:3.40.0.0
  - com.google.code.gson:gson:2.10.1